-- clean DimCustomer table
SELECT c.[CustomerKey] as [CustomerKey]
      --,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      ,c.[FirstName] as [FirstName]
      --,[MiddleName]
      ,c.[LastName] as [LastName]
	  ,c.FirstName + ' ' + c.LastName as [FullName]
      --,[NameStyle]
      --,[BirthDate]
      --,[MaritalStatus]
      --,[Suffix]
      ,CASE c.[Gender] WHEN 'M' THEN 'Male' WHEN 'F' THEN 'Female' END AS [Gender]
      --,[EmailAddress]
      --,[YearlyIncome]
      --,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
      --,[SpanishEducation]
      --,[FrenchEducation]
      --,[EnglishOccupation]
      --,[SpanishOccupation]
      --,[FrenchOccupation]
      --,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
      --,[AddressLine2]
      --,[Phone]
      ,c.[DateFirstPurchase] as [DateFirstPurchase]
      --,[CommuteDistance]
	  ,g.City as [Customer City]
  FROM [AdventureWorksDW2022].[dbo].[DimCustomer] as c
  LEFT JOIN [dbo].[DimGeography] as g
  ON c.GeographyKey = g.GeographyKey
  ORDER BY CustomerKey ASC